-- CRIANDO OS USUARIOS:

-- CRIANDO USUARIO DE BACKUP
CREATE USER "BACKUP"@"LOCALHOST" IDENTIFIED BY "123456";
GRANT SELECT ON DB_PILATES.* TO "BACKUP"@"LOCALHOST";
GRANT EVENT ON DB_PILATES.* TO "BACKUP"@"LOCALHOST";
GRANT LOCK TABLES ON DB_PILATES.* TO "BACKUP"@"LOCALHOST";
GRANT SHOW DATABASES ON *.* TO "BACKUP"@"LOCALHOST";


-- CRIANDO USUARIO DE VISUALIZAÇÃO
CREATE USER "VISUALIZACAO"@"LOCALHOST" IDENTIFIED BY "111222";
GRANT SELECT ON DB_PILATES.* TO "VISUALIZACAO"@"LOCALHOST";


-- CRIANDO USUARIO DA RECEPÇÃO
CREATE USER "RECEPCAO"@"LOCALHOST" IDENTIFIED BY "333444";
GRANT SELECT ON DB_PILATES.* TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_CLIENTES TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_CONTATO_CLIENTE TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_AGENDAMENTOS TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_VENDAS TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_VENDAS_PRODUTOS TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_STATUS_DO_PAGAMENTO TO "RECEPCAO"@"LOCALHOST";
GRANT INSERT ON TB_REGISTRO_DE_FREQUENCIA_NAS_AULAS TO "RECEPCAO"@"LOCALHOST";

GRANT UPDATE ON TB_CLIENTES TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_CONTATO_CLIENTE TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_AGENDAMENTOS TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_VENDAS TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_VENDAS_PRODUTOS TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_STATUS_DO_PAGAMENTO TO "RECEPCAO"@"LOCALHOST";
GRANT UPDATE ON TB_REGISTRO_DE_FREQUENCIA_NAS_AULAS TO "RECEPCAO"@"LOCALHOST";


-- CRIANDO USUARIO DO INSTRUTOR
CREATE USER "INSTRUTOR"@"LOCALHOST" IDENTIFIED BY "654321";
GRANT SELECT ON DB_PILATES.* TO "INSTRUTOR"@"LOCALHOST";
GRANT INSERT ON TB_AVALIACAO_FISICA TO "INSTRUTOR"@"LOCALHOST";
GRANT INSERT ON TB_VENDAS TO "INSTRUTOR"@"LOCALHOST";
GRANT INSERT ON TB_VENDAS_PRODUTOS TO "INSTRUTOR"@"LOCALHOST";
GRANT INSERT ON TB_AGENDAMENTOS TO "INSTRUTOR"@"LOCALHOST";
GRANT INSERT ON TB_REGISTRO_DE_FREQUENCIA_NAS_AULAS  TO "INSTRUTOR"@"LOCALHOST";

GRANT UPDATE ON TB_AVALIACAO_FISICA TO "INSTRUTOR"@"LOCALHOST";
GRANT UPDATE ON TB_VENDAS TO "INSTRUTOR"@"LOCALHOST";
GRANT UPDATE ON TB_VENDAS_PRODUTOS TO "INSTRUTOR"@"LOCALHOST";
GRANT UPDATE ON TB_AGENDAMENTOS TO "INSTRUTOR"@"LOCALHOST";
GRANT UPDATE ON TB_REGISTRO_DE_FREQUENCIA_NAS_AULAS  TO "INSTRUTOR"@"LOCALHOST";


-- CRIANDO USUARIO DO PROPRIETARIO
CREATE USER "PROPRIETARIO"@"LOCALHOST" IDENTIFIED BY "654321";
GRANT SELECT ON DB_PILATES.* TO "PROPRIETARIO"@"LOCALHOST";
GRANT INSERT ON DB_PILATES.* TO "PROPRIETARIO"@"LOCALHOST";
GRANT UPDATE ON DB_PILATES.* TO "PROPRIETARIO"@"LOCALHOST";
GRANT DELETE ON DB_PILATES.* TO "PROPRIETARIO"@"LOCALHOST";


-- CRIANDO USUARIO MASTER USER
CREATE USER "MASTERUSER"@"LOCALHOST" IDENTIFIED BY "321456";
GRANT ALL PRIVILEGES ON DB_PILATES.* TO "MASTERUSER"@"LOCALHOST";
